version: 'latest'

services:
  postgres:
    image: postgres:latest
    env_file: ./.env
    container_name: postgresx
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  postgres-data:
    driver: local
